<?php

include_once("../models/vRoot.php");
include_once("vTestsHelpers.php");
 
define("HAPPY_STR", '\'"\')(][\'"\'&Ā,ĐĘĶŃÓŚŰāđęķńóśűĂĎĚĹŅŒŠŲăěĺņœšųĄĒĻŇŕŢŸąēĢļňŖţŹĆĕģĽdŌŗźćĖĪľōŘťŻČėīŐřżčĮŁőŞŽįłőŞŽįłőŞŽįłşž\'"\')(][\'"\'&ĀĐĘĶŃÓŚŰāđęķńóśűĂĎĚĹŅŒŠŲăěĺņœšųĄĒĻŇŕŢŸąēĢļňŖţŹĆĕģĽdŌŗźćĖĪľōŘťŻČėīŐřżčĮŁőŞŽįłőŞŽįłőŞŽįłşž');
define("TEST_TIME1", "2001-02-03 01:23:45");
define("TEST_TIME2", "2015-01-02 02:33:45");
define("TEST_TIME3", "2013-03-02 03:44:45");
define("TEST_TIME4", "2014-05-02 04:55:45");
/**
 * Generated by PHPUnit_SkeletonGenerator on 2013-05-10 at 16:02:30.
 */
class vTaskDb_Test extends PHPUnit_Framework_TestCase {

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before each test is executed.
	 * 
	 * Assumes the test database was already created by installHelper::install($un, $pw, vDb::getTestDbName());
	 */
	protected function setUp() {
		//use test db - otherwise tests will run on the frameworks normal database
		vDb::loadTestDb();
		//$this->object = new ctg_run_checklist_item;
		print_ln(__METHOD__." starting.");
		$this->clean_up_db();
		print_ln(__METHOD__." complete.");
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after each test is executed.
	 */
	protected function tearDown() {
		
	}


	public function test_no_items_test() {
		print_ln(__METHOD__." starting.");
		$arr = vTaskDb::getTasks();
		$this->assertEquals(0, count($arr), "Everything should be deleted and table should be empty, but was not.");
		print_ln(__METHOD__." complete.");
	}

	/**
	 * Verify the sample generator is operating as we expect
	 */
	public function test_sample_9_test() {
		print_ln(__METHOD__." starting.");
		$test_item = new vTask();
		$index = 9;
		$test_item->task_id = $index;
		$test_item->task_status = $index+10;
		$test_item->module_ref = $index+100;
		$test_item->time_created = TEST_TIME1;
		$test_item->time_to_execute = TEST_TIME2;
		$test_item->time_start = TEST_TIME3;
		$test_item->time_completed = TEST_TIME4;
		$test_item->result_module_code = $index+1000;
		$test_item->result_module_msg = "rmm:$index".HAPPY_STR;
		$test_item->result_execution_level = $index+10000;
		$test_item->result_execution_code = $index+100000;
		$test_item->result_execution_msg = "rem:$index".HAPPY_STR;
		$test_item->module_startfile  = substr("sf:$index".HAPPY_STR, 0, vTaskDb::MODULE_STARTFILE_LENGTH);
		
		$compare_item = self::create_sample_item(9);
		$not_same = $this->compare_item($test_item, $compare_item);
		$this->assertTrue(empty($not_same), $not_same);
		print_ln(__METHOD__." complete.");
	}

	
	/**
	 * Verify we can add a sample to the database and get back the same data
	 */
	public function test_add_sample_test() {
		print_ln(__METHOD__." starting.");
		//first make sure it is empty
		$item_arr = vTaskDb::getTasks();
		$this->assertEquals(0, count($item_arr), "Expecting only no items here.");
		
		//add item
		$item1 = self::create_sample_item(4);
		$result = vTaskDb::insert($item1);
		$this->assertTrue(strlen($result) > 0, "Expected a last insert id number, but got '$result' on insert");
		$last_insert_id = $result;
		//load last_insert_id into sample so that it matches what was put in the db
		$item1->task_id = $last_insert_id;
		
		$item_arr = vTaskDb::getTasks();
		$this->assertEquals(1, count($item_arr), "Expecting only 1 sample here.");

		//verify created sample matches what is recovered from database
		$item_read = vTaskDb::getTask($last_insert_id);
		//make sure they match
		$not_same = $this->compare_item($item_read, $item1);
		if ($not_same) {
			print_ln("Sample:");
			var_export($item1);
			print_ln("As read:");
			var_export($item_read);
		}
		$this->assertTrue(empty($not_same), $not_same);
		
		print_ln(__METHOD__." complete.");
	}

	public function test_delete_sample_test() {
		print_ln(__METHOD__." starting.");
		$item1 = self::create_sample_item(1);
		$result = vTaskDb::insert($item1);
		$this->assertTrue(strlen($result) > 0, "Expected a last insert id number, but got '$result' on insert");
		
		$item_arr = vTaskDb::getTasks();
		$this->assertEquals(1, count($item_arr), "Expecting only 1 sample here.");

		//remove created item
		$del_result = vTaskDb::delete($result);
		$this->assertTrue($del_result, "Expected item to be deleted.");
		
		
		//check after deleting item
		$item_arr2 = vTaskDb::getTasks();
		$this->assertEquals(0, count($item_arr2), "Expecting no samples here.");

		print_ln(__METHOD__." complete.");
	}
	
	
			
	//============-----------> Helper Functions <----------------==============\\

		
	protected function clean_up_db() {
		$result = vTaskDb::wipeTasks();
		$this->assertTrue($result, "Could not clear database, check error log for details.");
	}

	protected static function create_sample_item($index=0) {
		$item = new vTask();
		
		//trim out items longer than are allowed (for comparison purposes)
		//ie. even though PDO will filter out the characters beyond what can be stored,
		//we want to compare what is inserted in the db to what is read from the db
		$item->task_id = $index;
		$item->task_status = $index+10;
		$item->module_ref = $index+100;
		$item->time_created = TEST_TIME1;
		$item->time_to_execute = TEST_TIME2;
		$item->time_start = TEST_TIME3;
		$item->time_completed = TEST_TIME4;
		$item->result_module_code = $index+1000;
		$item->result_module_msg = "rmm:$index".HAPPY_STR;
		$item->result_execution_level = $index+10000;
		$item->result_execution_code = $index+100000;
		$item->result_execution_msg = "rem:$index".HAPPY_STR;
		$item->module_startfile  = substr("sf:$index".HAPPY_STR, 0, vTaskDb::MODULE_STARTFILE_LENGTH);

		return $item;
	}

		
	/**
	 * Returns true if they do not match, empty if they do match
	 * @param type $er
	 */
	private function compare_to_sample($ct, $index = 0) {
		$ct_samp = self::create_sample_item($index);
		return self::compare_item($ct, $ct_samp);
	}

	/**
	 * Returns true if they do not match, empty if they do
	 * @param type $er
	 */
	protected static function compare_item($actual, $desired) {
		$not_same = "";
		//compare passed item to sample
		$not_same .= self::compare_helper($desired->task_id, $actual->task_id, vTaskDb::TASK_ID);
		$not_same .= self::compare_helper($desired->task_status, $actual->task_status, vTaskDb::TASK_STATUS);
		$not_same .= self::compare_helper($desired->module_ref, $actual->module_ref, vTaskDb::MODULE_REF);
		$not_same .= self::compare_helper($desired->time_created, $actual->time_created, vTaskDb::TIME_CREATED);
		$not_same .= self::compare_helper($desired->time_to_execute, $actual->time_to_execute, vTaskDb::TIME_TO_EXECUTE);
		$not_same .= self::compare_helper($desired->time_start, $actual->time_start, vTaskDb::TIME_START);
		$not_same .= self::compare_helper($desired->time_completed, $actual->time_completed, vTaskDb::TIME_COMPLETED);
		$not_same .= self::compare_helper($desired->result_module_code, $actual->result_module_code, vTaskDb::RESULT_MODULE_CODE);
		$not_same .= self::compare_helper($desired->result_module_msg, $actual->result_module_msg, vTaskDb::RESULT_MODULE_MSG);
		$not_same .= self::compare_helper($desired->result_execution_level, $actual->result_execution_level, vTaskDb::RESULT_EXECUTION_LEVEL);
		$not_same .= self::compare_helper($desired->result_execution_code, $actual->result_execution_code, vTaskDb::RESULT_EXECUTION_CODE);
		$not_same .= self::compare_helper($desired->result_execution_msg, $actual->result_execution_msg, vTaskDb::RESULT_EXECUTION_MSG);
		$not_same .= self::compare_helper(substr($desired->module_startfile, 0, vTaskDb::MODULE_STARTFILE_LENGTH), substr($actual->module_startfile, 0, vTaskDb::MODULE_STARTFILE_LENGTH), vTaskDb::MODULE_STARTFILE);
		return $not_same;
	}
	
	private static function compare_helper($desired, $actual, $field_name, $prefix = "") {
		$not_same = "";
		if ($desired.$prefix == $actual) {
			//value matches, do nothing
		} else {
			$not_same = "$field_name actual value [$actual] doesn't desired match [$desired$prefix]\n";
		}
		return $not_same;
	}

}
